// AUTO-GENERATED by KrossBuild — points this app at its managed Krossable Cloud backend.
// Do not edit by hand; re-provision the backend from Settings to regenerate.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zmtjgyshcxatharnrdvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdGpneXNoY3hhdGhhcm5yZHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2ODM1MzAsImV4cCI6MjA5OTI1OTUzMH0.1HSUO3XId_1ER3d1tCcFLcBYwjEC2VSquiN7OnmN9Uo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
